### PR TITLE
store ASN info for IPs

### PR DESCRIPTION
**Pull request by Brueggus**
This patch adds the functionality to store and display the autonomous system an IP belongs to

### CODE REVIEW

**Review by iandk — COMMENTED** [review]
Changes in the tailwind.css file will get overwritten by updating tailwind.
You should put custom CSS in the css/app.css file.

**Comment by Brueggus** [comment]
> Changes in the tailwind.css file will get overwritten by updating tailwind.
> You should put custom CSS in the css/app.css file.

Does this apply if I (also) change /tailwind.css ? (The code in public/app/css/tailwind.css was generated by `npm`)

**Comment by iandk** [comment]
When running the update command the existing tailwind.css will get replaced by the new version

**Comment by iandk** [comment]
Thanks, did you test it? Is it ready to merge?

**Comment by Brueggus** [comment]
> Thanks, did you test it? Is it ready to merge?

Yes, it should be fine. You can switch back and forth between ASN enabled/disabled and it works with and without asn information in the json data files.

**Pull request merged**
